// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAPIHealth() {
  return window['go']['main']['App']['CheckAPIHealth']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetCircuitStatus() {
  return window['go']['main']['App']['GetCircuitStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetSystemHealth() {
  return window['go']['main']['App']['GetSystemHealth']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InvokeAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['InvokeAgent'](arg1, arg2, arg3);
}

export function InvokeAgentChat(arg1, arg2) {
  return window['go']['main']['App']['InvokeAgentChat'](arg1, arg2);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function LoadModel(arg1) {
  return window['go']['main']['App']['LoadModel'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SendMessageStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessageStream'](arg1, arg2, arg3);
}

export function UnloadModel(arg1) {
  return window['go']['main']['App']['UnloadModel'](arg1);
}
